Added `add-all` / `remove-all` / `show` commands to the role management commands
RaenonX-PokemonSleep/eevee-sleep-discord-bot pull request #29
Opened 2024-06-09 11:59 UTC by Nokoyohei

#26

2024-06-09 12:04 UTC, RaenonX requested changes

2024-06-09 12:04 UTC, RaenonX commented on Eevee.Sleep.Bot/Utils/DiscordMessageMaker.cs
> +            .WithColor(Colors.Success)
Use `Colors.Info` instead.

2024-06-09 12:04 UTC, RaenonX commented on Eevee.Sleep.Bot/Utils/DiscordMessageMaker.cs
> +                value: roleIds.Length == 0 ?
Refactor all `string.Join()` calls to `DiscordExtension.MentionAllRoles()` and call it from there.

2024-06-09 12:04 UTC, RaenonX commented on Eevee.Sleep.Bot/Modules/SlashCommands/RoleManagementSlashModule.cs
> +        var user =
Refactor all `Context.User as SocketGuildUser ?? ...` calls to `DiscordExtension.AsGuildUser()` then call it like `Context.User.AsGuildUser()`.

2024-06-09 12:04 UTC, RaenonX commented
Also just make changes based on 1 commit (the current one)

2024-06-09 13:08 UTC, RaenonX commented on Eevee.Sleep.Bot/Utils/DiscordMessageMaker.cs
> +                value: roleIds.Length == 0 ?
And I think all `string.Join("\n")` can be further refactored to `StringExtension.mergeLines()` as well

2024-06-09 14:33 UTC, Nokoyohei commented
I don't know if it matches your image, but I tried to fix it.

2024-06-09 20:35 UTC, RaenonX requested changes
Yeah exactly these!

Actually for `MergeLines()` and `AsGuildUser()` refactoring, make them 2 separate commits (1 for `MergeLines()`; 1 for `AsGuildUser()`. Then, for each commit, change all original `string.Join("\n")` usages and `as SocketGuildUser ??` usages to use these 2 implementations.

2024-06-10 23:08 UTC, RaenonX requested changes
Also refactor all the other `string.Join(" / ",` calls to use `MergeLines()` and merge that change into their corresponding commit.

This should be the last change needed because I am not seeing socket user casting anywhere!

2024-06-11 13:51 UTC, Nokoyohei commented
Ok, probably all fixed.

2024-06-11 14:03 UTC, RaenonX approved these changes

2024-06-11 14:03 UTC, RaenonX commented
I added a few more commits myself, but the rest are good!

2024-06-11 14:05 UTC, merged